In [1]:
import numpy as np

In [2]:
list = [1,2,3,4]

In [3]:
a1 = np.array(list)

In [4]:
a1

array([1, 2, 3, 4])

In [5]:
print(a1)

[1 2 3 4]


In [6]:
a2 = np.array([[1,2,3,4] , [5,6,78]])
a2

<ipython-input-6-8ffb632b636a>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a2 = np.array([[1,2,3,4] , [5,6,78]])


array([list([1, 2, 3, 4]), list([5, 6, 78])], dtype=object)

In [7]:
a2 = np.array([[1,2,3,4] , [5,6,7,8]])
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
a2[0,3]

4

In [9]:
type(a2)

numpy.ndarray

In [10]:
a2.shape

(2, 4)

In [11]:
list  + 2

TypeError: can only concatenate list (not "int") to list

In [12]:
ar3 = np.arange(7)
ar3

array([0, 1, 2, 3, 4, 5, 6])

In [13]:
ar3.dtype

dtype('int32')

In [14]:
ar4 = np.linspace(2.5,5,6)
ar4

array([2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [15]:
r = np.range(10)
ar1 = ar.reshape(2,5)
ar1

AttributeError: module 'numpy' has no attribute 'range'

In [16]:
ar = np.arange(10)

In [17]:
ar1 = ar.reshape(2,5)
ar1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
ar1 = ar.reshape(5,2)
ar1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
ar = np.arange(10).reshape(2,5)
ar

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
ar = np.zeros([3,4])
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
ar = np.zeros([3,4], dtype - np.int64)

NameError: name 'dtype' is not defined

In [22]:
ar = np.zeros([3,4], dtype = np.int64)

In [23]:
ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [24]:
ar = np.ones[3,4], dtype = np.int64)

SyntaxError: unmatched ')' (<ipython-input-24-a66d1796a70d>, line 1)

In [25]:
ar = np.ones([3,4], dtype = np.int64)

In [26]:
ar

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [27]:
ar = np.random.rand(3,4)

In [28]:
ar

array([[0.49840878, 0.78314135, 0.67667464, 0.49807703],
       [0.38211736, 0.5049706 , 0.83292162, 0.06897815],
       [0.30109705, 0.79173605, 0.58683286, 0.88856762]])

In [29]:
ar = np.array([2,4,6,8,10,12,14,16])
ar[3:7]

array([ 8, 10, 12, 14])

In [30]:
ar[:5]

array([ 2,  4,  6,  8, 10])

In [31]:
ar[:-1]

array([ 2,  4,  6,  8, 10, 12, 14])

In [32]:
ar[2:7:2]

array([ 6, 10, 14])

In [33]:
ar = np.array([2,4,6,8,10], [12,14,16,18,20],[22,24,26,28,30],[32,34,36,38])
ar

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [34]:
ar = np.array([2,4,6,8,10], [12,14,16,18,20],[22,24,26,28,30],[32,34,36,38,40])

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [35]:
ar = np.array([[2,4,6,8,10], [12,14,16,18,20],[22,24,26,28,30],[32,34,36,38,40]])
ar

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [36]:
ar[1:3,3:5]

array([[18, 20],
       [28, 30]])

In [37]:
ar[1:3,]

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [38]:
ar[:,3:5]

array([[ 8, 10],
       [18, 20],
       [28, 30],
       [38, 40]])

In [39]:
ar[3,::-1]

array([40, 38, 36, 34, 32])

In [40]:
ar[-3:-1, -4::2]

array([[14, 18],
       [24, 28]])

In [41]:
lst1 = [1,2,3]

In [42]:
lst2 = [4,5,6]
lst3 = [[9,8,7]
       [6,5,4]]
lst4 = [[4],[5]]

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-42-0b47d9c93045>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  lst3 = [[9,8,7]


TypeError: list indices must be integers or slices, not tuple

In [43]:
lst3 = [[9,8,7]]

In [44]:
sar1 = np.vstack((lst1,lst2))

In [45]:
sar1

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
sar1.shape

(2, 3)

In [47]:
sar2 = np.vstack((lst2, lst3)

SyntaxError: unexpected EOF while parsing (<ipython-input-47-a3b68e6993fb>, line 1)

In [48]:
sar2 = np.vstack((lst2, lst3))

In [49]:
sar2

array([[4, 5, 6],
       [9, 8, 7]])

In [50]:
sar3 = np.hstack((lst3,lst4))
sar3

NameError: name 'lst4' is not defined

In [51]:
lst4 = [[4],[5]]

In [52]:
sar3 = np.hstack((lst3,lst4))
sar3

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2

In [53]:
arr = np.concatenate((lst1,lst2), axis = 0)

In [54]:
arr

array([1, 2, 3, 4, 5, 6])

In [55]:
arr = np.concatenate((lst1,lst2), axis = 1)
arr

AxisError: axis 1 is out of bounds for array of dimension 1

In [56]:
a= np.array([1,2,3,4])
b = np.array([3,4,0,1,-3])

In [57]:
cov_mat = np.cov(a,b)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 5

In [58]:
a= np.array([1,2,3,4,5])
b = np.array([3,4,0,1,-3])

In [59]:
cov_mat = np.cov(a,b)

In [60]:
cov_mat

array([[ 2.5 , -3.75],
       [-3.75,  7.5 ]])